npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 93EE556F-98F9-46F6-9438-533F697A778C
    npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
